/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as ApiV1WalletRouteImport } from './routes/api.v1.wallet'
import { Route as ApiV1RentsRouteImport } from './routes/api.v1.rents'
import { Route as ApiV1ProvidersRouteImport } from './routes/api.v1.providers'
import { Route as ApiV1AgentsRouteImport } from './routes/api.v1.agents'
import { Route as ApiV1RentsIdRouteImport } from './routes/api.v1.rents.$id'
import { Route as ApiV1ProvidersMineRouteImport } from './routes/api.v1.providers.mine'
import { Route as ApiV1RentsIdCancelRouteImport } from './routes/api.v1.rents.$id.cancel'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const ApiV1WalletRoute = ApiV1WalletRouteImport.update({
  id: '/api/v1/wallet',
  path: '/api/v1/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RentsRoute = ApiV1RentsRouteImport.update({
  id: '/api/v1/rents',
  path: '/api/v1/rents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ProvidersRoute = ApiV1ProvidersRouteImport.update({
  id: '/api/v1/providers',
  path: '/api/v1/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AgentsRoute = ApiV1AgentsRouteImport.update({
  id: '/api/v1/agents',
  path: '/api/v1/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RentsIdRoute = ApiV1RentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1RentsRoute,
} as any)
const ApiV1ProvidersMineRoute = ApiV1ProvidersMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => ApiV1ProvidersRoute,
} as any)
const ApiV1RentsIdCancelRoute = ApiV1RentsIdCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ApiV1RentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/provider': typeof ProviderRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/v1/agents': typeof ApiV1AgentsRoute
  '/api/v1/providers': typeof ApiV1ProvidersRouteWithChildren
  '/api/v1/rents': typeof ApiV1RentsRouteWithChildren
  '/api/v1/wallet': typeof ApiV1WalletRoute
  '/api/v1/providers/mine': typeof ApiV1ProvidersMineRoute
  '/api/v1/rents/$id': typeof ApiV1RentsIdRouteWithChildren
  '/api/v1/rents/$id/cancel': typeof ApiV1RentsIdCancelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/onboarding': typeof OnboardingRoute
  '/provider': typeof ProviderRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/api/v1/agents': typeof ApiV1AgentsRoute
  '/api/v1/providers': typeof ApiV1ProvidersRouteWithChildren
  '/api/v1/rents': typeof ApiV1RentsRouteWithChildren
  '/api/v1/wallet': typeof ApiV1WalletRoute
  '/api/v1/providers/mine': typeof ApiV1ProvidersMineRoute
  '/api/v1/rents/$id': typeof ApiV1RentsIdRouteWithChildren
  '/api/v1/rents/$id/cancel': typeof ApiV1RentsIdCancelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/provider': typeof ProviderRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/api/v1/agents': typeof ApiV1AgentsRoute
  '/api/v1/providers': typeof ApiV1ProvidersRouteWithChildren
  '/api/v1/rents': typeof ApiV1RentsRouteWithChildren
  '/api/v1/wallet': typeof ApiV1WalletRoute
  '/api/v1/providers/mine': typeof ApiV1ProvidersMineRoute
  '/api/v1/rents/$id': typeof ApiV1RentsIdRouteWithChildren
  '/api/v1/rents/$id/cancel': typeof ApiV1RentsIdCancelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/marketplace'
    | '/onboarding'
    | '/provider'
    | '/register'
    | '/sitemap.xml'
    | '/marketplace/$id'
    | '/marketplace/'
    | '/api/v1/agents'
    | '/api/v1/providers'
    | '/api/v1/rents'
    | '/api/v1/wallet'
    | '/api/v1/providers/mine'
    | '/api/v1/rents/$id'
    | '/api/v1/rents/$id/cancel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/onboarding'
    | '/provider'
    | '/register'
    | '/sitemap.xml'
    | '/marketplace/$id'
    | '/marketplace'
    | '/api/v1/agents'
    | '/api/v1/providers'
    | '/api/v1/rents'
    | '/api/v1/wallet'
    | '/api/v1/providers/mine'
    | '/api/v1/rents/$id'
    | '/api/v1/rents/$id/cancel'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/marketplace'
    | '/onboarding'
    | '/provider'
    | '/register'
    | '/sitemap.xml'
    | '/marketplace/$id'
    | '/marketplace/'
    | '/api/v1/agents'
    | '/api/v1/providers'
    | '/api/v1/rents'
    | '/api/v1/wallet'
    | '/api/v1/providers/mine'
    | '/api/v1/rents/$id'
    | '/api/v1/rents/$id/cancel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ProviderRoute: typeof ProviderRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiV1AgentsRoute: typeof ApiV1AgentsRoute
  ApiV1ProvidersRoute: typeof ApiV1ProvidersRouteWithChildren
  ApiV1RentsRoute: typeof ApiV1RentsRouteWithChildren
  ApiV1WalletRoute: typeof ApiV1WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/api/v1/wallet': {
      id: '/api/v1/wallet'
      path: '/api/v1/wallet'
      fullPath: '/api/v1/wallet'
      preLoaderRoute: typeof ApiV1WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rents': {
      id: '/api/v1/rents'
      path: '/api/v1/rents'
      fullPath: '/api/v1/rents'
      preLoaderRoute: typeof ApiV1RentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/providers': {
      id: '/api/v1/providers'
      path: '/api/v1/providers'
      fullPath: '/api/v1/providers'
      preLoaderRoute: typeof ApiV1ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/agents': {
      id: '/api/v1/agents'
      path: '/api/v1/agents'
      fullPath: '/api/v1/agents'
      preLoaderRoute: typeof ApiV1AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/rents/$id': {
      id: '/api/v1/rents/$id'
      path: '/$id'
      fullPath: '/api/v1/rents/$id'
      preLoaderRoute: typeof ApiV1RentsIdRouteImport
      parentRoute: typeof ApiV1RentsRoute
    }
    '/api/v1/providers/mine': {
      id: '/api/v1/providers/mine'
      path: '/mine'
      fullPath: '/api/v1/providers/mine'
      preLoaderRoute: typeof ApiV1ProvidersMineRouteImport
      parentRoute: typeof ApiV1ProvidersRoute
    }
    '/api/v1/rents/$id/cancel': {
      id: '/api/v1/rents/$id/cancel'
      path: '/cancel'
      fullPath: '/api/v1/rents/$id/cancel'
      preLoaderRoute: typeof ApiV1RentsIdCancelRouteImport
      parentRoute: typeof ApiV1RentsIdRoute
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface ApiV1ProvidersRouteChildren {
  ApiV1ProvidersMineRoute: typeof ApiV1ProvidersMineRoute
}

const ApiV1ProvidersRouteChildren: ApiV1ProvidersRouteChildren = {
  ApiV1ProvidersMineRoute: ApiV1ProvidersMineRoute,
}

const ApiV1ProvidersRouteWithChildren = ApiV1ProvidersRoute._addFileChildren(
  ApiV1ProvidersRouteChildren,
)

interface ApiV1RentsIdRouteChildren {
  ApiV1RentsIdCancelRoute: typeof ApiV1RentsIdCancelRoute
}

const ApiV1RentsIdRouteChildren: ApiV1RentsIdRouteChildren = {
  ApiV1RentsIdCancelRoute: ApiV1RentsIdCancelRoute,
}

const ApiV1RentsIdRouteWithChildren = ApiV1RentsIdRoute._addFileChildren(
  ApiV1RentsIdRouteChildren,
)

interface ApiV1RentsRouteChildren {
  ApiV1RentsIdRoute: typeof ApiV1RentsIdRouteWithChildren
}

const ApiV1RentsRouteChildren: ApiV1RentsRouteChildren = {
  ApiV1RentsIdRoute: ApiV1RentsIdRouteWithChildren,
}

const ApiV1RentsRouteWithChildren = ApiV1RentsRoute._addFileChildren(
  ApiV1RentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ProviderRoute: ProviderRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiV1AgentsRoute: ApiV1AgentsRoute,
  ApiV1ProvidersRoute: ApiV1ProvidersRouteWithChildren,
  ApiV1RentsRoute: ApiV1RentsRouteWithChildren,
  ApiV1WalletRoute: ApiV1WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
